---
- name: Get golang binary tarball
  get_url:
    url: "{{ golang_download_url }}"
    dest: "/tmp/golang.tgz"

- name: Create directory
  file:
    path: "{{ golang_install_prefix }}"
    state: directory
    recurse: yes

- name: Expand tarball
  become: yes
  unarchive:
    copy: no
    src: "/tmp/golang.tgz"
    dest: "{{ golang_install_prefix }}"

- name: Remove tarball
  file:
    path: "/tmp/golang.tgz"
    state: absent

- name: Change permission
  become: yes
  template:
    src: "etc/profile.d/golang.sh"
    dest: "/etc/profile.d/golang.sh"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Copy binary
  become: yes
  file:
    src: "{{ golang_install_prefix }}/go/bin/go"
    dest: "/usr/local/bin/go"
    owner: "root"
    group: "root"
    state: "link"
