---
- name: Setup my MacOSX
  hosts: all
  connection: local
  vars_files:
    - vars/{{ stage }}.yml
  roles:
    - { role: env,           tags: [ env ] }
    - { role: homebrew,      tags: [ homebrew ] }
    - { role: go,            tags: [ go ] }
    - { role: ruby,          tags: [ ruby ] }
    - { role: python2,       tags: [ python2 ] }
    - { role: python3,       tags: [ python3 ] }
