---
- name: Setup
  hosts: all
  connection: local
  vars_files:
    - vars/{{ stage }}.yml
  roles:
    - role: mac
      tags:
        - mac
      when: ansible_os_family == 'Darwin'
    - role: ubuntu
      tags:
        - ubuntu
      when: ansible_os_family == 'Debian'
    - { role: languages,    tags: [ languages ] }
    - { role: commons,      tags: [ commons ] }
