---
- name: Setup
  hosts: all
  connection: local
  vars_files:
    - vars/{{ stage }}.yml
  roles:
    - { role: os,           tags: [ os ] }
    - { role: languages,    tags: [ languages ] }
    - { role: commons,      tags: [ commons ] }
