---
platform: darwin
inputs:
  - name: repository
run:
  path: /bin/bash
  dir: repository
  args:
    - -c
    - |
      export PATH=/usr/local/bin:$PATH
      ansible-playbook \
        -i inventories/${STAGE} \
        main.yml
