---
platform: darwin
inputs:
  - name: repository
run:
  path: /bin/bash
  dir: repository
  args:
    - -c
    - |
      ansible-playbook \
        -i inventories/personal \
        --extra-vars role_name=${ROLE_NAME} \
        ci/playbooks/role.yml
