---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
inputs:
  - name: repository
outputs:
  - name: workspace
run:
  path: /bin/bash
  args:
    - -c
    - |
      cat << EOF > "workspace/Dockerfile"
      FROM ubuntu:xenial
      RUN apt-get update && \
            apt-get install -y software-properties-common && \
            apt-add-repository ppa:gophers/archive && \
            apt-add-repository ppa:ansible/ansible && \
            apt-get update && \
            apt-get install -y \
              ansible \
              golang-1.9-go \
              python-dev \
              python-pip \
              python3-dev \
              python3-pip \
              ruby2.3 \
              ruby2.3-dev
      EOF
