---
- name: Already exist directory
  shell: "[ ! -e {{ item }} ] && echo exist"
  register: is_exist
  changed_when: False
  ignore_errors: True

- name: Create directory
  shell: "mkdir -p {{ item }}"
  when: is_exist == "exist"
