---
- name: Clone git repository
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items: "{{ default_git_repositories + git_repositories }}"

- name: Create Symlink
  shell: |
    rm -rf {{ item.dest }}; \
    ln -s {{ item.src }} {{ item.dest }}
  with_items: "{{ default_symlinks + symlinks }}"
