---
- include: directories.yml
  with_items: "{{ default_directories + directories }}"

- name: Clone git repository
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items: "{{ default_git_repositories + git_repositories }}"

- name: Create symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    state: link
  with_items: "{{ default_symlinks + symlinks }}"

- include: variables.yml
  with_items: "{{ default_variables + variables }}"

- name: Erase fish_user_path
  shell: fish --command 'set --erase fish_user_paths'
  check_mode: no
  changed_when: False
  ignore_errors: True

- name: Apply PATH
  shell: fish --command 'set --universal fish_user_paths {{ item }} $fish_user_paths'
  changed_when: False
  with_items: "{{ paths }}"
