---
- include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- include_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- name: Install Python2 package
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ default_python2_packages + python2_packages }}"

- name: Install Python3 package
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    executable: pip3
  with_items: "{{ default_python3_packages + python3_packages }}"
