---
- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Add homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install homebrew packages
  homebrew:
    name: "{{ item.name | default(item)  }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ homebrew_packages }}"

- name: Create Caskroom directory
  file:
    path: /usr/local/Caskroom
    state: directory
    owner: sakuraba
    group: admin
    mode: 0755

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_packages }}"

- name: Setup OS X defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ mac_os_defaults }}"
