---
resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/raba-jp/OS_Setup

jobs:
  - name: OS roles
    plan:
      - get: repository
        trigger: true
      - aggregate:
        - task: Ubuntu 16.04
          file: repository/ci/tasks/role.yml
          params:
            ROLE_NAME: ubuntu
        - task: macOS
          file: repository/ci/tasks/role_mac.yml
          params:
            ROLE_NAME: mac
  - name: Language roles
    plan:
      - get: repository
        trigger: true
      - aggregate:
        - task: Python
          file: repository/ci/tasks/role.yml
          params:
            ROLE_NAME: python
        - task: Ruby
          file: repository/ci/tasks/role.yml
          params:
            ROLE_NAME: ruby
        - task: Rust
          file: repository/ci/tasks/role.yml
          params:
            ROLE_NAME: rust
  - name: Go role
    plan:
      - get: repository
        trigger: true
      - aggregate:
        - task: Mac
          file: repository/ci/tasks/role_mac.yml
          params:
            ROLE_NAME: go
        - task: Ubuntu 16.04
          file: repository/ci/tasks/role.yml
          params:
            ROLE_NAME: go
  - name: commons role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: commons
  - name: All
    plan:
      - get: repository
        trigger: true
        passed:
          - OS roles
          - Language roles
          - commons role
      - task: ubuntu personal
        file: repository/ci/tasks/main_ubuntu.yml
        params:
          STAGE: personal
      - task: ubuntu work
        file: repository/ci/tasks/main_ubuntu.yml
        params:
          STAGE: work
      - task: darwin personal
        file: repository/ci/tasks/main_darwin.yml
        params:
          STAGE: personal
      - task: darwin work
        file: repository/ci/tasks/main_darwin.yml
        params:
          STAGE: work
