---
resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/raba-jp/OS_Setup

jobs:
  - name: ubuntu role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: ubuntu
  - name: mac role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: mac
  - name: go role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: go
  - name: python role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: python
  - name: ruby role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: ruby
  - name: rust role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: rust
