---
resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/raba-jp/OS_Setup

jobs:
  - name: Ubuntu
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: ubuntu
  - name: macOS
    serial_groups: [ homebrew ]
    plan:
      - get: repository
        trigger: true
      - aggregate:
        - task: run
          file: repository/ci/tasks/role_mac.yml
          params:
            ROLE_NAME: mac
  - name: Go
    serial_groups: [ homebrew ]
    plan:
      - get: repository
        trigger: true
      - aggregate:
        - task: Mac
          file: repository/ci/tasks/role_mac.yml
          params:
            ROLE_NAME: go
        - task: Ubuntu 16.04
          file: repository/ci/tasks/role.yml
          params:
            ROLE_NAME: go
  - name: Python
    serial_groups: [ homebrew ]
    plan:
      - get: repository
        trigger: true
      - aggregate:
        - task: Mac
          file: repository/ci/tasks/role_mac.yml
          params:
            ROLE_NAME: python
        - task: Ubuntu 16.04
          file: repository/ci/tasks/role.yml
          params:
            ROLE_NAME: python
  - name: Ruby
    plan:
      - get: repository
        trigger: true
      - task: Mac
        file: repository/ci/tasks/role_mac.yml
        params:
          ROLE_NAME: ruby
      - task: Ubuntu 16.04
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: ruby
  - name: Rust
    plan:
      - get: repository
        trigger: true
      - aggregate:
        - task: Mac
          file: repository/ci/tasks/role_mac.yml
          params:
            ROLE_NAME: rust
        - task: Ubuntu 16.04
          file: repository/ci/tasks/role.yml
          params:
            ROLE_NAME: rust
  - name: commons
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role.yml
        params:
          ROLE_NAME: commons
  - name: All
    plan:
      - get: repository
        trigger: true
        passed:
          - Ubuntu
          - macOS
          - Go
          - Python
          - Rust
          - Ruby
          - commons
      - task: ubuntu personal
        file: repository/ci/tasks/main_ubuntu.yml
        params:
          STAGE: personal
      - task: ubuntu work
        file: repository/ci/tasks/main_ubuntu.yml
        params:
          STAGE: work
      - task: darwin personal
        file: repository/ci/tasks/main_darwin.yml
        params:
          STAGE: personal
      - task: darwin work
        file: repository/ci/tasks/main_darwin.yml
        params:
          STAGE: work
