---
resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/raba-jp/OS_Setup

jobs:
  - name: ubuntu role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role_ubuntu.yml
  - name: mac role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role_mac.yml
  - name: go role
    plan:
      - get: repository
        trigger: true
      - task: run
        file: repository/ci/tasks/role_go.yml
