---
default_homebrew_taps:
  - homebrew/dupes
  - homebrew/services
  - caskroom/cask
  - caskroom/fonts
  - neovim/neovim
  - go-delve/delve

default_homebrew_packages:
  - boost
  - ctags
  - exa
  - fish
  - git
  - ghq
  - name: gnu-sed
    install_options: with-default-names
  - go
  - jq
  - nkf
  - less
  - neovim
  - peco
  - python
  - python3
  - reattach-to-user-namespace
  - terminal-notifier
  - sshrc
  - the_silver_searcher
  - tig
  - tmux
  - tree
  - wget

default_homebrew_cask_packages:
  - appcleaner
  - bettertouchtool
  - betterzipql
  - cheatsheet
  - docker
  - font-myrica
  - google-chrome
  - quicklook-csv
  - qlmarkdown
  - slack
  - the-unarchiver
  - vagrant
  - virtualbox
