---
- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Add homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ default_homebrew_taps + homebrew_taps }}"

- name: Install homebrew packages
  homebrew:
    name: "{{ item.name | default(item)  }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ default_homebrew_packages + homebrew_packages }}"

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ default_homebrew_cask_packages + homebrew_cask_packages }}"
