---
- name: Get AppStore account status
  shell: mas account
  register: app_store_account_status
  failed_when: app_store_account_status.rc > 1
  changed_when: False

- name: Sign in to AppStore when id and password are provided.
  shell: 'mas signin "{{ app_store_id }}" "{{ app_store_password }}"'
  register: app_store_signin_status
  when:
    - app_store_account_status.rc == 1
    - app_store_id != ''
    - app_store_password != ''

- name: List installed MAS apps.
  command: mas list
  register: app_store_list
  check_mode: no
  changed_when: false

- name: Ensure configured AppStore apps are installed.
  command: mas install "{{ item }}"
  with_items: "{{ app_store_applications }}"
  when: "'{{ item }}' not in app_store_list.stdout"

- name: Upgrade all apps (if configured).
  command: mas upgrade
  when: app_store_upgrade
