---
- name: Create directory
  shell: "mkdir -p {{ item }}"
  with_items: "{{ directories }}"

- name: Clone git repository
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items: "{{ git_repositories }}"

- name: Create symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    state: link
  with_items: "{{ symlinks }}"
